services:
  - type: web
    name: ai-stock-advisor
    env: python
    region: virginia
    plan: free
    pythonVersion: 3.12.6       # <- specifies Python version
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /api/status
